version: '3'

services:

  database-postgres:
    image: postgres:14
    container_name: database-postgres
    volumes:
      - ./postgres:/data/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_MULTIPLE_DATABASES=car-rental
      - PGDATA=/data/postgres
    ports:
      - 5432:5432
    restart: always

  database-mongo:
    image: mongo
    container_name: database-mongo
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    restart: always

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    links:
      - database-postgres

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=database-mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    ports:
      - 5051:80
    links:
      - database-mongo

  zookeeper:
    image: 'wurstmeister/zookeeper'
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: 'wurstmeister/kafka'
    ports:
      - 9092:9092
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "access_payment_topic,change_request_status_topic"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
    restart: always

  authorization-microservice:
    container_name: authorization-microservice
    depends_on:
      - database-postgres
    build:
      context: ./authorization
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    restart: no
    environment:
      DATABASE_URL: jdbc:postgresql://database-postgres/car-rental?currentSchema=authorizations
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root
      MICROSERVICE_NAME: AUTHORIZATION_MICROSERVICE
      AUTHORIZATION_MICROSERVICE_URL: http://authorization-microservice:8081

  car-microservice:
    container_name: car-microservice
    depends_on:
      - database-postgres
    image: tomcat:10.1.7-jdk17
    restart: no
    volumes:
      - ./car/run/target/car-run.war:/usr/local/tomcat/webapps/car-run.war
    ports:
      - 8082:8080
    environment:
      DATABASE_URL: jdbc:postgresql://database-postgres/car-rental?currentSchema=car
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root
      MICROSERVICE_NAME: CAR_MICROSERVICE
      AUTHORIZATION_MICROSERVICE_URL: http://authorization-microservice:8080/car-run
      CARS_CATALOG_PAGE_SIZE: 4

  rental-microservice:
    container_name: rental-microservice
    depends_on:
      - database-postgres
    build:
      context: ./rental
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    restart: no
    environment:
      DATABASE_URL: jdbc:postgresql://database-postgres/car-rental?currentSchema=rental
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root
      MICROSERVICE_NAME: RENTAL_MICROSERVICE
      AUTHORIZATION_MICROSERVICE_URL: http://authorization-microservice:8081
      CAR_MICROSERVICE_URL: http://car-microservice:8082/car-run
      PROFILE_ADMIN_REQUESTS_PAGE_SIZE: 5
      PROFILE_ADMIN_REFUNDS_PAGE_SIZE: 5
      PROFILE_USER_REFUNDS_PAGE_SIZE: 5

volumes:
  data: {}
