server:
  port: ${MICROSERVICE_PORT:9191}

spring:
  application:
    name: API-GATEWAY
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: AUTHORIZATION-MICROSERVICE
          uri: ${AUTHORIZATION_MICROSERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/authorization/**
        - id: CAR-MICROSERVICE
          uri: ${CAR_MICROSERVICE_URI:http://localhost:8082/car-run}
          predicates:
            - Path=/cars/**,/colors/**,/conditions/**,/registrations/**,statuses/**,/types/**
        - id: RENTAL-MICROSERVICE
          uri: ${RENTAL_MICROSERVICE_URI:http://localhost:8083}
          predicates:
            - Path=/profile/**,/blacklist/**,/requests/**,/car/**,/catalog/**,/profile/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true